"""
Carousel Overlay Engine
========================
Core renderer. Do not edit this file.
All creative decisions live in:
  - assets/stylesheet.py      → fonts, colors, sizes, scrim settings
  - assets/captions/[ep].py   → per-frame text copy and placement

Usage:
  python scripts/overlay_engine.py \\
    --input  /path/to/images \\
    --output /path/to/output \\
    --captions assets/captions/episode-01.py

Or import and call render_carousel() directly.
"""

import os
import sys
import argparse
import importlib.util
import textwrap
from PIL import Image, ImageDraw, ImageFont, ImageFilter

try:
    import emoji as emoji_lib
    EMOJI_AVAILABLE = True
except ImportError:
    EMOJI_AVAILABLE = False

EMOJI_FONT_PATH = "/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf"

# ─── Config loading ───────────────────────────────────────────────
# Stylesheet: look in ../assets/ relative to this script, then fall back
# to same directory (legacy behaviour)
_SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
_SKILL_ROOT  = os.path.dirname(_SCRIPT_DIR)
_ASSETS_DIR  = os.path.join(_SKILL_ROOT, "assets")

# Add assets dir first so stylesheet.py there takes precedence
sys.path.insert(0, _ASSETS_DIR)
sys.path.insert(0, _SCRIPT_DIR)

from stylesheet import (FONT_PRIMARY, FONT_SIZE, COLOR, SCRIM, LAYOUT, OUTPUT,
                        IG_SAFE, SHOW_SAFE_ZONE_GUIDE, TEXT_CONTRAST, TEXT_BACKING)
try:
    from stylesheet import FONT_STYLIZED
except ImportError:
    FONT_STYLIZED = FONT_PRIMARY
try:
    from stylesheet import FONT_CTA
except ImportError:
    FONT_CTA = FONT_PRIMARY

# FRAMES loaded dynamically — set by load_captions() at runtime
FRAMES = []

def load_captions(captions_path: str):
    """Dynamically load a captions file and return its FRAMES list."""
    spec   = importlib.util.spec_from_file_location("captions", captions_path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.FRAMES


# ─── Font cache ──────────────────────────────────────────────────

_font_cache = {}

def get_font(style: str, stylized: bool = False) -> ImageFont.FreeTypeFont:
    cache_key = f"{style}_{'S' if stylized else 'P'}"
    if cache_key not in _font_cache:
        if stylized:
            path = FONT_STYLIZED
            size = FONT_SIZE.get("stylized", int(FONT_SIZE.get(style, 110) * 1.15))
        elif style == "cta":
            path = FONT_CTA
            size = FONT_SIZE.get("cta", 72)
        else:
            path = FONT_PRIMARY
            size = FONT_SIZE.get(style, 110)
        _font_cache[cache_key] = ImageFont.truetype(path, size)
    return _font_cache[cache_key]


# ─── Contrast methods ────────────────────────────────────────────

def apply_contrast(img: Image.Image, text: str, font, color_rgba: tuple,
                   x: int, y: int, method: str = None) -> Image.Image:
    """
    Draw text onto img using the specified contrast method.
    method: "stroke" | "dual_shadow" | "halo_shadow" | "stroke_shadow"
    Falls back to TEXT_CONTRAST["method"] if None.
    Returns the composited image.
    """
    cfg    = TEXT_CONTRAST
    method = method or cfg["method"]
    out    = img.convert("RGBA")

    if method == "stroke":
        d = ImageDraw.Draw(out)
        d.text((x, y), text, font=font, fill=color_rgba,
               stroke_width=cfg["stroke_width"],
               stroke_fill=cfg["stroke_color"])

    elif method == "dual_shadow":
        # Wide soft shadow
        wide = Image.new("RGBA", out.size, (0, 0, 0, 0))
        wd   = ImageDraw.Draw(wide)
        off  = cfg["shadow_wide_offset"]
        wd.text((x + off, y + off), text, font=font, fill=(0, 0, 0, cfg["shadow_wide_alpha"]))
        wide = wide.filter(ImageFilter.GaussianBlur(radius=cfg["shadow_wide_blur"]))
        out  = Image.alpha_composite(out, wide)
        # Tight hard shadow
        tight = Image.new("RGBA", out.size, (0, 0, 0, 0))
        td    = ImageDraw.Draw(tight)
        off2  = cfg["shadow_tight_offset"]
        td.text((x + off2, y + off2), text, font=font, fill=(0, 0, 0, cfg["shadow_tight_alpha"]))
        out = Image.alpha_composite(out, tight)
        d   = ImageDraw.Draw(out)
        d.text((x, y), text, font=font, fill=color_rgba)

    elif method == "halo_shadow":
        # Blurred halo — wraps letterforms in a glow
        halo = Image.new("RGBA", out.size, (0, 0, 0, 0))
        hd   = ImageDraw.Draw(halo)
        hd.text((x, y), text, font=font, fill=(0, 0, 0, cfg["halo_alpha"]))
        halo = halo.filter(ImageFilter.GaussianBlur(radius=cfg["halo_blur"]))
        out  = Image.alpha_composite(out, halo)
        # Tight shadow underneath for edge definition
        tight = Image.new("RGBA", out.size, (0, 0, 0, 0))
        td    = ImageDraw.Draw(tight)
        off   = cfg["shadow_tight_offset"]
        td.text((x + off, y + off), text, font=font, fill=(0, 0, 0, cfg["shadow_tight_alpha"]))
        out = Image.alpha_composite(out, tight)
        d   = ImageDraw.Draw(out)
        d.text((x, y), text, font=font, fill=color_rgba)

    elif method == "stroke_shadow":
        # Soft shadow + thin stroke — hybrid
        shadow = Image.new("RGBA", out.size, (0, 0, 0, 0))
        sd     = ImageDraw.Draw(shadow)
        off    = cfg["shadow_wide_offset"]
        sd.text((x + off, y + off), text, font=font, fill=(0, 0, 0, 160))
        shadow = shadow.filter(ImageFilter.GaussianBlur(radius=14))
        out    = Image.alpha_composite(out, shadow)
        d      = ImageDraw.Draw(out)
        d.text((x, y), text, font=font, fill=color_rgba,
               stroke_width=max(3, cfg["stroke_width"] // 2),
               stroke_fill=cfg["stroke_color"])

    else:
        # Unknown method — fall back to stroke
        d = ImageDraw.Draw(out)
        d.text((x, y), text, font=font, fill=color_rgba,
               stroke_width=cfg["stroke_width"],
               stroke_fill=cfg["stroke_color"])

    return out


# ─── Scrim drawing ───────────────────────────────────────────────

def draw_scrim(img: Image.Image, side: str, height_pct: float, opacity_max: int) -> Image.Image:
    """Draw a gradient scrim on a copy of the image."""
    w, h = img.size
    scrim_h = int(h * height_pct)

    scrim = Image.new("RGBA", (w, scrim_h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(scrim)

    for i in range(scrim_h):
        if side == "top":
            # Darkest at top, fades down
            alpha = int(opacity_max * (1 - i / scrim_h))
        else:
            # Darkest at bottom, fades up
            alpha = int(opacity_max * (i / scrim_h))
        draw.line([(0, i), (w, i)], fill=(0, 0, 0, alpha))

    result = img.convert("RGBA")
    if side == "top":
        result.paste(scrim, (0, 0), scrim)
    else:
        result.paste(scrim, (0, h - scrim_h), scrim)

    return result


# ─── Text drawing ────────────────────────────────────────────────

def wrap_text(text: str, max_chars: int) -> list[str]:
    """Wrap text at word boundaries."""
    return textwrap.wrap(text, width=max_chars)


def measure_text_block(lines: list[str], font: ImageFont.FreeTypeFont, spacing: int) -> tuple[int, int]:
    """Return (width, height) of a multi-line text block."""
    dummy = Image.new("RGBA", (10, 10))
    draw = ImageDraw.Draw(dummy)
    max_w = 0
    total_h = 0
    for i, line in enumerate(lines):
        bbox = draw.textbbox((0, 0), line, font=font)
        lw = bbox[2] - bbox[0]
        lh = bbox[3] - bbox[1]
        max_w = max(max_w, lw)
        total_h += lh
        if i < len(lines) - 1:
            total_h += spacing
    return max_w, total_h


def split_text_emoji(text: str):
    """Split text into (segment, is_emoji) pairs for mixed rendering."""
    if not EMOJI_AVAILABLE:
        return [(text, False)]
    result = []
    current = ""
    for char in text:
        if emoji_lib.is_emoji(char):
            if current:
                result.append((current, False))
                current = ""
            result.append((char, True))
        else:
            current += char
    if current:
        result.append((current, False))
    return result


def measure_mixed_line(text: str, font: ImageFont.FreeTypeFont, emoji_font) -> tuple[int, int]:
    """Measure width and height of a line with mixed text/emoji."""
    dummy = Image.new("RGBA", (10, 10))
    draw = ImageDraw.Draw(dummy)
    total_w = 0
    max_h = 0
    for segment, is_emoji in split_text_emoji(text):
        if not segment.strip() and is_emoji is False:
            # Space
            bbox = draw.textbbox((0, 0), segment, font=font)
            total_w += bbox[2] - bbox[0]
            max_h = max(max_h, bbox[3] - bbox[1])
        elif is_emoji and emoji_font:
            bbox = draw.textbbox((0, 0), segment, font=emoji_font)
            total_w += bbox[2] - bbox[0]
            max_h = max(max_h, bbox[3] - bbox[1])
        else:
            clean = emoji_lib.replace_emoji(segment, replace='') if EMOJI_AVAILABLE else segment
            if clean:
                bbox = draw.textbbox((0, 0), clean, font=font)
                total_w += bbox[2] - bbox[0]
                max_h = max(max_h, bbox[3] - bbox[1])
    return total_w, max_h


def draw_text_block(
    draw: ImageDraw.ImageDraw,
    lines: list[str],
    font: ImageFont.FreeTypeFont,
    color_rgba: tuple,
    img_size: tuple[int, int],
    position: str,
    spacing: int,
    padding_x: int,
    padding_y: int,
    img_ref: Image.Image = None,
):
    """Draw centered multi-line text anchored to top or bottom, with emoji support."""
    w, h = img_size
    shadow_offset = max(3, font.size // 30)

    # Load emoji font if available
    emoji_font = None
    if EMOJI_AVAILABLE and os.path.exists(EMOJI_FONT_PATH):
        try:
            emoji_font = ImageFont.truetype(EMOJI_FONT_PATH, int(font.size * 0.85))
        except Exception:
            pass

    # Measure total block height
    line_heights = []
    for line in lines:
        if EMOJI_AVAILABLE and emoji_font:
            _, lh = measure_mixed_line(line, font, emoji_font)
        else:
            bbox = draw.textbbox((0, 0), line, font=font)
            lh = bbox[3] - bbox[1]
        line_heights.append(max(lh, font.size))

    block_h = sum(line_heights) + spacing * (len(lines) - 1)

    if position == "top":
        y_start = padding_y
    else:
        y_start = h - padding_y - block_h

    for li, line in enumerate(lines):
        lh = line_heights[li]

        if EMOJI_AVAILABLE and emoji_font:
            # Measure full line width for centering
            line_w, _ = measure_mixed_line(line, font, emoji_font)
        else:
            clean_line = emoji_lib.replace_emoji(line, replace='').strip() if EMOJI_AVAILABLE else line
            bbox = draw.textbbox((0, 0), clean_line, font=font)
            line_w = bbox[2] - bbox[0]

        x_cursor = (w - line_w) // 2

        # Render each segment
        for segment, is_emoji in split_text_emoji(line):
            if is_emoji and emoji_font and img_ref is not None:
                # Render emoji on a temp surface and paste (color emoji needs RGBA composite)
                bbox = draw.textbbox((0, 0), segment, font=emoji_font)
                seg_w = bbox[2] - bbox[0]
                seg_h = bbox[3] - bbox[1]
                emoji_surface = Image.new("RGBA", (seg_w + 10, lh + 10), (0, 0, 0, 0))
                ed = ImageDraw.Draw(emoji_surface)
                ed.text((5, 5), segment, font=emoji_font, embedded_color=True)
                # Paste onto image
                paste_x = x_cursor
                paste_y = y_start + (lh - seg_h) // 2
                img_ref.paste(emoji_surface, (paste_x, paste_y), emoji_surface)
                x_cursor += seg_w
            else:
                clean_seg = emoji_lib.replace_emoji(segment, replace='').strip() if EMOJI_AVAILABLE else segment
                if not clean_seg:
                    # Just spaces
                    if segment:
                        bbox = draw.textbbox((0, 0), segment, font=font)
                        x_cursor += bbox[2] - bbox[0]
                    continue
                bbox = draw.textbbox((0, 0), clean_seg, font=font)
                seg_w = bbox[2] - bbox[0]
                seg_h = bbox[3] - bbox[1]
                y_text = y_start + (lh - seg_h) // 2
                # Shadow
                draw.text((x_cursor + shadow_offset, y_text + shadow_offset),
                          clean_seg, font=font, fill=(0, 0, 0, 160))
                draw.text((x_cursor, y_text), clean_seg, font=font, fill=color_rgba)
                x_cursor += seg_w

        y_start += lh + spacing


# ─── Main render ─────────────────────────────────────────────────

def draw_text_block_safe(
    draw: ImageDraw.ImageDraw,
    lines: list[str],
    font: ImageFont.FreeTypeFont,
    color_rgba: tuple,
    safe_bounds: tuple[int, int, int, int],
    img_size: tuple[int, int],
    position: str,
    spacing: int,
    padding_x: int,
    padding_y: int,
    img_ref: Image.Image = None,
    stylized: bool = False,
    contrast: str = None,
    font_path: str = None,   # explicit path used for shrink loop — overrides auto-detection
):
    """
    Safe-zone-aware text renderer with subtitle stability + reading UX.

    READING UX RULES APPLIED:
    - Fixed Y anchors: top/bottom overlays always land at the same Y every frame.
      Reader's eye parks there after frame 2 and stops hunting.
    - 60% line width cap: keeps lines to 1-2 eye fixations on mobile.
    - Auto-shrink: font reduces until all lines fit within width budget.
    - Hard 2-line cap from LAYOUT["max_lines"].
    - Stylized/middle frames bypass anchors — editorial rules apply instead.
    """
    safe_x1, safe_y1, safe_x2, safe_y2 = safe_bounds
    frame_w, frame_h = img_size

    stroke_pad = TEXT_CONTRAST.get("stroke_width", 7) + 4

    # Width budget: 60% of frame for regular text, full safe width for stylized
    if stylized or position == "middle":
        max_line_px = (safe_x2 - safe_x1) - (stroke_pad * 2)
    else:
        max_line_px = int(frame_w * LAYOUT.get("line_width_pct", 0.60)) - (stroke_pad * 2)

    emoji_font = None
    if EMOJI_AVAILABLE and os.path.exists(EMOJI_FONT_PATH):
        try:
            emoji_font = ImageFont.truetype(EMOJI_FONT_PATH, int(font.size * 0.85))
        except Exception:
            pass

    def measure_line(line, fnt):
        if EMOJI_AVAILABLE and emoji_font:
            lw, lh = measure_mixed_line(line, fnt, emoji_font)
        else:
            clean = emoji_lib.replace_emoji(line, replace='').strip() if EMOJI_AVAILABLE else line
            d = ImageDraw.Draw(Image.new("RGBA", (10, 10)))
            bb = d.textbbox((0, 0), clean, font=fnt)
            lw, lh = bb[2] - bb[0], bb[3] - bb[1]
        return lw, max(lh, fnt.size)

    # Re-wrap lines to fit within pixel width budget at the current font size.
    # Font size never changes — only line breaks do.
    def wrap_to_pixel_width(text_lines, fnt, budget_px):
        """Re-wrap already-split lines so no rendered line exceeds budget_px."""
        result = []
        for line in text_lines:
            words = line.split()
            if not words:
                continue
            current = words[0]
            for word in words[1:]:
                trial = current + " " + word
                lw, _ = measure_line(trial, fnt)
                if lw <= budget_px:
                    current = trial
                else:
                    result.append(current)
                    current = word
            result.append(current)
        return result

    # Step 1: wrap to pixel budget at full font size
    lines = wrap_to_pixel_width(lines, font, max_line_px)

    # Step 2: if wrapping still gives 3+ lines, shrink font until ≤ 2 lines
    if len(lines) > LAYOUT.get("max_lines", 2):
        current_font = font
        # Use explicit path if provided, otherwise auto-detect
        shrink_path = font_path or (FONT_STYLIZED if stylized else FONT_PRIMARY)
        for _ in range(20):
            candidate = wrap_to_pixel_width(
                [" ".join(lines)], current_font, max_line_px
            )
            if len(candidate) <= LAYOUT.get("max_lines", 2):
                font  = current_font
                lines = candidate
                break
            new_size = max(40, int(current_font.size * 0.92))
            if new_size == current_font.size:
                lines = lines[:LAYOUT.get("max_lines", 2)]
                break
            try:
                current_font = ImageFont.truetype(shrink_path, new_size)
            except Exception:
                break

    # Measure final block
    line_heights, line_widths = [], []
    for line in lines:
        lw, lh = measure_line(line, font)
        line_heights.append(lh)
        line_widths.append(lw)

    block_h = sum(line_heights) + spacing * (len(lines) - 1)

    # Fixed Y anchors — subtitle stability
    # top/bottom use absolute frame-% anchors so position is identical every frame.
    # middle/stylized use editorial 58% placement within safe zone.
    if position == "middle" or stylized:
        safe_h  = safe_y2 - safe_y1
        y_start = safe_y1 + int(safe_h * 0.58) - block_h // 2
    elif position == "top":
        y_start = int(frame_h * LAYOUT.get("anchor_top_pct", 0.12))
    else:  # bottom
        y_start = int(frame_h * LAYOUT.get("anchor_bottom_pct", 0.76)) - block_h

    # Draw lines
    for li, line in enumerate(lines):
        lh     = line_heights[li]
        line_w = line_widths[li]
        x      = (frame_w - line_w) // 2   # center on full frame width

        clean_line = emoji_lib.replace_emoji(line, replace='').strip() if EMOJI_AVAILABLE else line

        if clean_line:
            img_ref = apply_contrast(
                img_ref, clean_line, font, color_rgba,
                x=x, y=y_start, method=contrast
            )
            draw = ImageDraw.Draw(img_ref)

        if EMOJI_AVAILABLE and emoji_font:
            ex = x
            for segment, is_emoji in split_text_emoji(line):
                if is_emoji and img_ref is not None:
                    bb = draw.textbbox((0, 0), segment, font=emoji_font)
                    sw, sh = bb[2] - bb[0], bb[3] - bb[1]
                    es = Image.new("RGBA", (sw + 10, lh + 10), (0, 0, 0, 0))
                    ed = ImageDraw.Draw(es)
                    ed.text((5, 5), segment, font=emoji_font, embedded_color=True)
                    img_ref.paste(es, (ex + line_w - sw, y_start + (lh - sh) // 2), es)
                    draw = ImageDraw.Draw(img_ref)
                else:
                    cs = emoji_lib.replace_emoji(segment, replace='').strip() if EMOJI_AVAILABLE else segment
                    if cs:
                        bb = draw.textbbox((0, 0), cs, font=font)
                        ex += bb[2] - bb[0]

        y_start += lh + spacing

    return img_ref




def draw_safe_zone_guide(img: Image.Image) -> Image.Image:
    """Draw a visible safe zone border for QA. Controlled by SHOW_SAFE_ZONE_GUIDE in stylesheet."""
    w, h = img.size
    overlay = img.copy().convert("RGBA")
    draw = ImageDraw.Draw(overlay, "RGBA")

    sz = IG_SAFE
    x1 = int(w * sz["left_clear_pct"])
    y1 = int(h * sz["top_clear_pct"])
    x2 = int(w * (1 - sz["right_clear_pct"]))
    y2 = int(h * (1 - sz["bottom_clear_pct"]))

    # Danger zones — red tint
    draw.rectangle([0,  0,  w,  y1], fill=(220, 40, 40, 80))   # top
    draw.rectangle([0,  y2, w,  h],  fill=(220, 40, 40, 80))   # bottom
    draw.rectangle([x2, y1, w,  y2], fill=(220, 120, 40, 80))  # right buttons

    # Safe zone border — green dashed feel via thin rect
    draw.rectangle([x1, y1, x2, y2], outline=(80, 220, 120, 200), width=6)

    # Labels
    font_path = FONT_PRIMARY
    try:
        lbl_font = ImageFont.truetype(font_path, 44)
        draw.text((x1 + 20, y1 + 20), "✓ IG SAFE ZONE", font=lbl_font, fill=(80, 220, 120, 230))
        draw.text((w//2 - 200, 30), "▲ PROFILE BAR", font=lbl_font, fill=(255, 255, 255, 200))
        draw.text((w//2 - 250, y2 + 30), "▼ CAPTION / LIKES / NAV", font=lbl_font, fill=(255, 255, 255, 200))
        draw.text((x2 + 10, h//2 - 80), "◀ BTNS", font=lbl_font, fill=(255, 200, 100, 200))
    except Exception:
        pass

    return Image.alpha_composite(img.convert("RGBA"), overlay.convert("RGBA"))


def render_frame(frame_config: dict, input_dir: str, output_dir: str):
    filename = frame_config["file"]
    overlays = frame_config.get("overlays", [])

    src_path = os.path.join(input_dir, filename)
    if not os.path.exists(src_path):
        print(f"  ⚠  Skipping {filename} — not found in {input_dir}")
        return

    img = Image.open(src_path).convert("RGBA")
    w, h = img.size

    # ── IG Safe zone bounds ──────────────────────────────────────
    sz = IG_SAFE
    safe_x1   = int(w * sz["left_clear_pct"])
    safe_y1   = int(h * sz["top_clear_pct"])
    safe_x2   = int(w * (1 - sz["right_clear_pct"]))
    safe_y2   = int(h * (1 - sz["bottom_clear_pct"]))
    safe_w    = safe_x2 - safe_x1

    # Inner padding within safe zone
    padding_x = int(w * LAYOUT["padding_x_pct"])
    padding_y = int(h * LAYOUT["padding_y_pct"])

    for overlay in overlays:
        if overlay.get("scrim", False):
            img = draw_scrim(
                img,
                side=overlay.get("scrim_side", "bottom"),
                height_pct=SCRIM["height_pct"],
                opacity_max=SCRIM["opacity_max"],
            )

        stylized  = overlay.get("stylized", False)
        contrast  = overlay.get("contrast", None)

        # Per-overlay font path override (e.g. Oi for frame 10 closer)
        font_override = overlay.get("font", None)
        if font_override:
            size = FONT_SIZE.get(overlay["style"], 110)
            try:
                font = ImageFont.truetype(font_override, size)
            except Exception:
                font = get_font(overlay["style"], stylized=stylized)
        else:
            font = get_font(overlay["style"], stylized=stylized)

        color = COLOR[overlay["color"]]
        text  = overlay["text"]
        pos   = overlay["position"]

        lines = wrap_text(text, LAYOUT["max_chars"])
        draw  = ImageDraw.Draw(img)

        img = draw_text_block_safe(
            draw=draw,
            lines=lines,
            font=font,
            color_rgba=color,
            safe_bounds=(safe_x1, safe_y1, safe_x2, safe_y2),
            img_size=(w, h),
            position=pos,
            spacing=LAYOUT["line_spacing"],
            padding_x=padding_x,
            padding_y=padding_y,
            img_ref=img,
            stylized=stylized,
            contrast=contrast,
            font_path=font_override,
        ) or img

    # Optional QA guide
    if SHOW_SAFE_ZONE_GUIDE:
        img = draw_safe_zone_guide(img)

    name, ext = os.path.splitext(filename)
    out_name = f"{name}{OUTPUT['suffix']}.png"
    out_path = os.path.join(output_dir, out_name)
    img.convert("RGB").save(out_path, format=OUTPUT["format"])
    print(f"  ✓  {filename}  →  {out_name}")


def render_carousel(input_dir: str, output_dir: str, captions_path: str = None):
    global FRAMES

    # Resolve captions — explicit path, or default location
    if captions_path:
        frames = load_captions(captions_path)
    else:
        # Try assets/captions/default.py, then fall back to legacy captions.py
        default_paths = [
            os.path.join(_ASSETS_DIR, "captions", "default.py"),
            os.path.join(_SCRIPT_DIR, "captions.py"),
        ]
        frames = None
        for p in default_paths:
            if os.path.exists(p):
                frames = load_captions(p)
                break
        if frames is None:
            print("Error: no captions file found. Pass --captions path/to/captions.py")
            sys.exit(1)

    FRAMES = frames
    os.makedirs(output_dir, exist_ok=True)

    print(f"\nCarousel Overlay Engine")
    print(f"Input:    {input_dir}")
    print(f"Output:   {output_dir}")
    print(f"Captions: {captions_path or '(default)'}")
    print(f"Frames:   {len(FRAMES)}\n")

    for frame in FRAMES:
        render_frame(frame, input_dir, output_dir)

    print(f"\nDone. {len(FRAMES)} frames rendered → {output_dir}\n")


# ─── CLI ─────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Carousel Overlay Engine")
    parser.add_argument("--input",    default=".",        help="Directory containing source images")
    parser.add_argument("--output",   default="./output", help="Directory for rendered frames")
    parser.add_argument("--captions", default=None,       help="Path to captions .py file")
    args = parser.parse_args()
    render_carousel(args.input, args.output, args.captions)

